### PR TITLE
implementing workflow loading and saving

### PR DESCRIPTION
**Pull request by Cryaaa**
Hey Robert @haesleinhuepf,
this is the first stably working implementation of loading (and saving) workflows from the napari assistant. I did some test with workflows generated using the nsbatwm functions in the assistant and it was working for various test workflows. One function I copied and modified slightly from one of your repositories (make_gui is what it was called in your repository) and I couldn't add the reference to it in the docstring so maybe you can add it afterwards? Let me know what you think of the PR!

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hi Ryan @Cryaaa ,

awesome, thanks so much for working on this! I'm also happy about the high code-quality! Comments, variable and function names, excellent, really good. Thanks.

Just one question: Do you want to add yourself to the list of authors? (optional, your choice)
https://github.com/haesleinhuepf/napari-assistant/blob/main/setup.py#L35

Otherwise, I'll merge soon.

Thanks again!
Best,
Robert

**Comment by haesleinhuepf** [comment]
# [Codecov](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) Report
> Merging [#1](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) (1b71011) into [main](https://codecov.io/gh/haesleinhuepf/napari-assistant/commit/fd102f0d0c51c7e32f605aebbf8388acf2ca1317?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) (fd102f0) will **decrease** coverage by `6.17%`.
> The diff coverage is `2.81%`.

[Impacted file tree graph](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase)

```diff
@@            Coverage Diff             @@
##             main       #1      +/-   ##
==========================================
- Coverage   38.42%   32.25%   -6.18%     
==========================================
  Files          11       12       +1     
  Lines         661      803     +142     
==========================================
+ Hits          254      259       +5     
- Misses        407      544     +137     
```


| [Impacted Files](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) | Coverage Δ | |
|---|---|---|
| [napari\_assistant/\_workflow\_io\_utility.py](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fd29ya2Zsb3dfaW9fdXRpbGl0eS5weQ==) | `0.00% <0.00%> (ø)` | |
| [napari\_assistant/\_gui/\_Assistant.py](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fZ3VpL19Bc3Npc3RhbnQucHk=) | `48.68% <23.52%> (-3.17%)` | :arrow_down: |
| [napari\_assistant/\_gui/\_button\_grid.py](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fZ3VpL19idXR0b25fZ3JpZC5weQ==) | `96.96% <0.00%> (+3.03%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase). Last update [fd102f0...1b71011](https://codecov.io/gh/haesleinhuepf/napari-assistant/pull/1?src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase).

**Comment by Cryaaa** [comment]
@haesleinhuepf,
thanks first of all! I would gladly add myself to the authors and will do it in the next commit :)

**Comment by haesleinhuepf** [comment]
Awesome @Cryaaa ! I also invited you to collaborate on the project. You can then work in this repository and don't need a fork anymore. Thanks again!

**Pull request merged**
