### PR TITLE
Operation select after workflow loading

### LINKED ISSUE #2: Workflow loading: cluttering the overlay
Everytime a workflow is loaded from disc all the widgets are added simultaneously filling up the widget panel to the righthand side. It could be better to only display the widget which generates the layer that is currently selected. Furthermore, the actual layout could be optimised to make the layout more visually pleasing.

### LINKED ISSUE #9: Workflow  loading throws error when using clesperanto functions
I just tried saving and loading a workflow that containted `clesperanto` functions. 

Loading doesn't work. There is this error instead:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File c:\structure\code\napari-assistant\napari_assistant\_gui\_Assistant.py:310, in Assistant.load_workflow(self=, filename='C:/structure/code/napari-segment-blobs-and-things-with-membranes/test.yaml')
    307     filename, _ = QFileDialog.getOpenFileName(self, "Import workflow ...", ".", "*.yaml")
    308 self.workflow = _io_yaml_v1.load_workflow(filename)
--> 310 initialise_root_functions(self.workflow,
        self.workflow = 
        self = 
        self._viewer = Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(29.5, 255.5, 255.5), zoom=1.0557617187500001, angles=(4.790685039054108, -6.611146334177069, 136.73847153098146), perspective=0.0, interactive=True), cursor=Cursor(position=(49.23985573484544, 316.8327878819127, 524.145081062303), scaled=True, size=1, style=), dims=Dims(ndim=3, ndisplay=3, last_used=0, range=((0.0, 60.0, 1.0), (0.0, 256.0, 1.0), (0.0, 256.0, 1.0)), current_step=(30, 128, 128), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=-1, shape=(-1, -1), enabled=True), layers=[], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position=, font_size=10, unit=None), text_overlay=TextOverlay(visible=False, color=(0.5, 0.5, 0.5, 1.0), font_size=10, position=, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=, transform_drag=, transform_final=, transform=, allow_new_selection=True, selected_vertex=None)), help='', status='nuclei [ 49 317 524]', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_move_callbacks=[.mouse_move at 0x00000247AA2385E0>], mouse_drag_callbacks=[.mouse_drag at 0x00000247AA226700>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': .hold_to_lock_aspect_ratio at 0x00000247AA226A60>, 'Control-Shift-R': , 'Control-Shift-A': })
    311                           self._viewer)
    312 load_remaining_workflow(workflow=self.workflow,
    313                         viewer=self._viewer)

File c:\structure\code\napari-assistant\napari_assistant\_workflow_io_utility.py:75, in initialise_root_functions(workflow=, viewer=Viewer(axes=Axes(visible=False, labels=True, col...._transform_active_layer at 0x00000247A9B8DEE0>}))
     72     viewer.window.add_dock_widget(widget, name = wf_step_name[10:] + ' - SELECT INPUT')
     74 # calling the widget with the correct input images
---> 75 widget()
        widget =  Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage]>

File ~\miniconda3\envs\bio_39\lib\site-packages\magicgui\widgets\_function_gui.py:293, in FunctionGui.__call__(self=, update_widget=False, *args=(), **kwargs={})
    284     missing = match.groups()[0] if match else ""
    285     msg = (
    286         f"{e} in call to '{self._callable_name}{sig}'.\n"
    287         "To avoid this error, you can bind a value or callback to the "
   (...)
    291         f"    def {self._callable_name}{sig}: ..."
    292     )
--> 293     raise TypeError(msg) from None
        msg = "missing a required argument: 'source' in call to 'gaussian_blur(source: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage], *, destination: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage] = None, sigma_x: float = 3.0, sigma_y: float = 3.0, sigma_z: float = 0.0) -> Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage]'.\nTo avoid this error, you can bind a value or callback to the parameter:\n\n    gaussian_blur.source.bind(value)\n\nOr use the 'bind' option in the magicgui decorator:\n\n    @magicgui(source={'bind': value})\n    def gaussian_blur(source: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage], *, destination: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage] = None, sigma_x: float = 3.0, sigma_y: float = 3.0, sigma_z: float = 0.0) -> Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage]: ..."
    295 if update_widget:
    296     self._auto_call, before = False, self._auto_call

TypeError: missing a required argument: 'source' in call to 'gaussian_blur(source: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage], *, destination: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage] = None, sigma_x: float = 3.0, sigma_y: float = 3.0, sigma_z: float = 0.0) -> Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage]'.
To avoid this error, you can bind a value or callback to the parameter:

    gaussian_blur.source.bind(value)

Or use the 'bind' option in the magicgui decorator:

    @magicgui(source={'bind': value})
    def gaussian_blur(source: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage], *, destination: Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage] = None, sigma_x: float = 3.0, sigma_y: float = 3.0, sigma_z: float = 0.0) -> Union[numpy.ndarray, pyclesperanto_prototype._tier0._pycl.OCLArray, pyopencl._cl.Image, pyclesperanto_prototype._tier0._pycl._OCLImage]: ...
```

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi Ryan @Cryaaa ,

I'm sending this PR as attempt to fix #9 and would love to hear your opinion!

It's just 90% well-thought-through. I hope it doesn't break to many things. The one major change is that I removed a GUI-generating function from your code and call an older one instead. Thus, after loading a workflow, we see now a GUI that looks like before saving the workflow. Example:

Before (current main branch):
image

New (after this PR):
image

The only problem I have now is that the pre-selected layer is not correct:
image

closes #2 
closes #9 
According to the yaml-file (link below), it should select the result of Gaussian blur:
image

It may be related to some type-changes: I _think_ the GUI-code I removed was somehow using LayerData, while the GUI I'm using now uses Layers. Thus, there must be code somewhere that compares Layers with LayerData and doesn't find a match. Maybe you immediately know what I mean. Otherwise, I'm happy to explain in a meeting. :-)

I'm also adding this test-workflow. After opening "blobs" from `File > Open Samples > clEsperanto`, it should be loadable.
[test_.zip](https://github.com/haesleinhuepf/napari-assistant/files/8459328/test_.zip)

Also note: this will only work with this [napari-workflows branch](https://github.com/haesleinhuepf/napari-workflows/pull/21) installed.

No hurry btw.

Best,
Robert

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
## [Codecov](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) Report
Attention: Patch coverage is `5.40541%` with `140 lines` in your changes missing coverage. Please review.
> Project coverage is 29.18%. Comparing base [(`2f0d159`)](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/commit/2f0d15923fdd5193aa274e5b50bbb196b31328f2?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) to head [(`4be61af`)](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/commit/4be61af49193aa430078ca10b58f369848d7109d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase).
> Report is 192 commits behind head on main.

| [Files with missing lines](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) | Patch % | Lines |
|---|---|---|
| [napari\_assistant/\_workflow\_io\_utility.py](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&filepath=napari_assistant%2F_workflow_io_utility.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fd29ya2Zsb3dfaW9fdXRpbGl0eS5weQ==) | 0.00% | [67 Missing :warning: ](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) |
| [napari\_assistant/\_gui/\_category\_widget.py](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&filepath=napari_assistant%2F_gui%2F_category_widget.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fZ3VpL19jYXRlZ29yeV93aWRnZXQucHk=) | 10.34% | [52 Missing :warning: ](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) |
| [napari\_assistant/\_categories.py](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&filepath=napari_assistant%2F_categories.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fY2F0ZWdvcmllcy5weQ==) | 13.33% | [13 Missing :warning: ](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) |
| [napari\_assistant/\_gui/\_Assistant.py](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&filepath=napari_assistant%2F_gui%2F_Assistant.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase#diff-bmFwYXJpX2Fzc2lzdGFudC9fZ3VpL19Bc3Npc3RhbnQucHk=) | 0.00% | [8 Missing :warning: ](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase) |

<details><summary>Additional details and impacted files</summary>


```diff
@@            Coverage Diff             @@
##             main      #11      +/-   ##
==========================================
- Coverage   30.15%   29.18%   -0.98%     
==========================================
  Files          12       12              
  Lines         892      932      +40     
==========================================
+ Hits          269      272       +3     
- Misses        623      660      +37     
```

</details>

[:umbrella: View full report in Codecov by Sentry](https://app.codecov.io/gh/haesleinhuepf/napari-assistant/pull/11?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Robert+Haase).

<details><summary> :rocket: New features to boost your workflow: </summary>

- :snowflake: [Test Analytics](https://docs.codecov.com/docs/test-analytics): Detect flaky tests, report on failures, and find test suite problems.
</details>

**Comment by Cryaaa** [comment]
Hey @haesleinhuepf,
I unfortunately can't use the napari assistant at all when using this branch since everytime I try to add a processing step (like noise removal) I get this error:
Traceback (most recent call last):

  File "c:\users\ryans\onedrive\documents\bia pol stuff\napari workflow repositories\napari-assistant\napari_assistant\_gui\_Assistant.py", line 156, in _on_item_clicked
    self._activate(CATEGORIES.get(item.text()))
  File "c:\users\ryans\onedrive\documents\bia pol stuff\napari workflow repositories\napari-assistant\napari_assistant\_gui\_Assistant.py", line 173, in _activate
    gui = make_gui_for_category(category, self.seach_field.text(), self._viewer, button_size=self.button_size_spin_box.value())
  File "c:\users\ryans\onedrive\documents\bia pol stuff\napari workflow repositories\napari-assistant\napari_assistant\_gui\_category_widget.py", line 404, in make_gui_for_category
    op_name_widget.value = operation_name
  File "C:\Users\ryans\anaconda3\envs\np_workflows_v1\lib\site-packages\magicgui\widgets\_bases\categorical_widget.py", line 47, in value
    raise ValueError(
ValueError: None is not a valid choice. must be in ('Gaussian (scikit-image, nsbatwm)', 'gaussian_blur (clesperanto)', 'mean_box (clesperanto)', 'mean_sphere (clesperanto)', 'Median (scipy, nsbatwm)', 'median_box (clesperanto)', 'median_sphere (clesperanto)', 'Percentile (scipy, nsbatwm)')

I'm guessing the added code seems to break some old functionality? I'm looking into it but am unsure of how to deal with it...

**Comment by Cryaaa** [comment]
Hey @haesleinhuepf!
I have done some cleaning up and simplification, but think that maybe now is the time for somebody else to look through the code. There are some notebooks and workflows which I introduced in the docs folder, which can be deleted after reviewing and testing is done. Maybe Johannes could look into the code (although I cannot tag him yet). Also I do not know how to make the codecov tests pass. Maybe I could also write some tests for loading workflows using the notebooks I used.... Let me know what you think and maybe we can schedule a meeting.

**Comment by Cryaaa** [comment]
@haesleinhuepf,
This PR is ready for mering from my side. Loading now works for all functions implemented in the napari assistant (including pyclesperanto functions).

**Comment by haesleinhuepf** [comment]
Yes. Awesome, thanks for taking care of this @Cryaaa !

**Pull request closed without merging**
